### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by ProxyPlayerHD** [byteworksinc/ORCA-Pascal#20]
The README says that you can download precompiled binaries even though the release section doesn't exist if you follow the URL.
So the only option is to build it yourself, but there is no Malefile or even build instructions with a list of tools required.

So how is this repo intended to be used? I would love to be able to build it on modern x86 to have a Pascal cross compiler for the 65816.

**Comment by MikeW50** [comment]
I'll take a look at the link later, but:

This compiler is designed to run on an Apple IIgs. Parts are written in assembly language. It assumes the existence of libraries and a link editor, also written in assembly language for the Apple IIgs. While porting it to another system is possible, it is definitely not as easy as rebuilding on another OS.

As for the make file, the Apple IIgs development environment does not use make, it uses shell scripts. Those run under the ORCA shell in the Apple IIgs. Porting is possible, but not trivial.

**Comment by ProxyPlayerHD** [comment]
sad, i was hoping the assembly files were not required for the actual compiler and that was entirely written in pascal so you could just an existing compiler or itself to make either a native or cross compiler for the 65816.

oh well, that still leaves the question on how you build it on native hardware. i'm not very familiar with the IIgs ecosystem, so it'd be nice if the readme included a rough walkthrough on what you need to do to build and test the compiler on an emulator like GSPlus (or actual hardware).

**Comment by MikeW50** [comment]
I have updated the links to point to the Opus ][ collection, where you can get the full development environment for the ORCA products.

Once you have the build environment set up you can build the compiler using the shell script named make. See the reference manual (included with the Opus ][ package) for basic instructions on using the build environment and running shell scripts.

**Comment by ProxyPlayerHD** [comment]
thank you!
